# Base mob without sprinting capability, used for ghosts and other entities that shouldn't be able to sprint
- type: entity
  save: false
  id: BaseMobNoSprint
  abstract: true
  components:
  - type: Sprite
    noRot: true
    drawdepth: Mobs
  - type: MobCollision
  - type: Physics
    bodyType: KinematicController
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.35
        density: 50
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: Clickable
  - type: InteractionOutline
  - type: InputMover
  - type: Input
    context: "human"
  - type: LagCompensation
  - type: MobMover
  - type: Actions
  - type: Alerts
  - type: Appearance
  - type: RotationVisuals
    defaultRotation: 0
    horizontalRotation: 0
  - type: DoAfter
  - type: Examiner
  - type: Eye
  - type: ContentEye
  - type: CameraRecoil
  - type: MindContainer
  - type: MovementSpeedModifier
  - type: RequireProjectileTarget
    active: False
  # Note: No Sprinter component - this is intentional
